name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android:
    name: Android Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Android APK
      run: flutter build apk

  ios:
    name: iOS Build & Test
    runs-on: macos-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS App
      run: flutter build ios --no-codesign

  macos:
    name: macOS Build & Test
    runs-on: macos-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'

    - name: Update macOS Deployment Target
      run: |
        sed -i '' 's/platform :osx, .*/platform :osx, '\''11.0'\''/' macos/Podfile

    - name: Install dependencies
      run: flutter pub get

    - name: Build macOS App
      run: flutter build macos

  web:
    name: Web Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Web App
      run: flutter build web