name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android:
    name: Android Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Dry-run Android Build
      run: flutter build apk --dry-run

  ios:
    name: iOS Build & Test
    runs-on: macos-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Dry-run iOS Build
      run: flutter build ios --no-codesign --dry-run

  macos:
    name: macOS Build & Test
    runs-on: macos-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Dry-run macOS Build
      run: flutter build macos --dry-run

  web:
    name: Web Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Dry-run Web Build
      run: flutter build web --dry-run
